export const DataProduct = [
    {
        id:"1",
        img:"/product1.png",
        name:"Mixed Nuts Berries Pack",
        dish:"Dried Fruits",
        prise:"$56.00",
        prise2:"$45.00",
        sale:"Sale",
    },
    {
        id:"2",
        img:"/product2.png",
        name:"Multi Grain Combo Cookies",
        dish:"Cookies",
        prise:"$30.00",
        prise2:"$25.00",
        sale:"Sale",
    },
    {
        id:"3",
        img:"/product3.png",
        name:"Fresh Mango juice pack",
        dish:"Foods",
        prise:"$65.00",
        prise2:"$46.00",
        sale:"",
    },
    {
        id:"4",
        img:"/product4.png",
        name:"Dates Value Fresh Pouch",
        dish:"Dried Fruits",
        prise:"$85.00",
        prise2:"$78.00",
        sale:"Sale",
    },
    {
        id:"5",
        img:"/product5.png",
        name:"Stick Fiber Masala Magic",
        dish:"Foods",
        prise:"$50.00",
        prise2:"$45.00",
        sale:"NEW",
    },
];

export const DataProducts = [
    {
        id:"1",
        img:"/product1.png",
        name:"Mixed Nuts Berries Pack",
        dish:"Dried Fruits",
        prise:"$56.00",
        prise2:"$45.00",
        sale:"Sale",
    },
    {
        id:"2",
        img:"/product2.png",
        name:"Multi Grain Combo Cookies",
        dish:"Cookies",
        prise:"$30.00",
        prise2:"$25.00",
        sale:"Sale",
    },
    {
        id:"3",
        img:"/product3.png",
        name:"Fresh Mango juice pack",
        dish:"Foods",
        prise:"$65.00",
        prise2:"$46.00",
        sale:"",
    },
    {
        id:"4",
        img:"/product4.png",
        name:"Dates Value Fresh Pouch",
        dish:"Dried Fruits",
        prise:"$85.00",
        prise2:"$78.00",
        sale:"Sale",
    },
    {
        id:"5",
        img:"/product5.png",
        name:"Stick Fiber Masala Magic",
        dish:"Foods",
        prise:"$50.00",
        prise2:"$45.00",
        sale:"NEW",
    },
    {
        id:"6",
        img:"/product6.png",
        name:"Natural Hub Cherry Karonda",
        dish:"Fresh Fruit",
        prise:"$65.00",
        prise2:"$49.00",
        sale:"NEW",
    },
    {
        id:"7",
        img:"/product3.png",
        name:"Fresh Mango juice pack",
        dish:"Foods",
        prise:"$65.00",
        prise2:"$46.00",
        sale:"",
    },
    {
        id:"8",
        img:"/product7.png",
        name:"Fresh Organic Ginger Pack",
        dish:"Tuber root",
        prise:"$3.00",
        prise2:"$2.00",
        sale:"",
    },
    {
        id:"9",
        img:"/product8.png",
        name:"Natural Hub Cherry Karonda",
        dish:"Foods",
        prise:"$65.00",
        prise2:"$49.00",
        sale:"NEW",
    },
    {
        id:"10",
        img:"/product9.png",
        name:"Fresh Mango juice pack",
        dish:"Fresh Fruit",
        prise:"$21.00",
        prise2:"$20.00",
        sale:"",
    },
];

export const DataAbout = [
    {
        id:"1",
        title:"Free Shipping",
        dish:"Free shipping on all US order or order above $200",
        icon:"/Icon1.png",
    },
    {
        id:"2",
        title:"24X7 Support",
        dish:"Contact us 24 hours a day, 7 days a week",
        icon:"/Icon2.png",
    },
    {
        id:"3",
        title:"30 Days Return",
        dish:"Simply return it within 30 days for an exchange",
        icon:"/Icon3.png",
    },
    {
        id:"4",
        title:"Payment Secure",
        dish:"Contact us 24 hours a day, 7 days a week",
        icon:"/Icon4.png",
    },
];

export const DataProductt = [
    {
        id:"1",
        img:"/card1.png",
        title:"Healthy Nutmix, 200g Pack",
        dish:"Driedfruit",
        prise:"$45.00",
        prise2:"$42.00",
    },
    {
        id:"2",
        img:"/card2.png",
        title:"Ginger - Organic",
        dish:"vegetables",
        prise:"$65.00",
        prise2:"$62.00",
    },
    {
        id:"3",
        img:"/card3.png",
        title:"Lemon - Seedless",
        dish:"vegetables",
        prise:"$45.00",
        prise2:"$42.00",
    },
    {
        id:"4",
        img:"/card4.png",
        title:"Organic fresh tomato",
        dish:"vegetables",
        prise:"$30.00",
        prise2:"$25.00",
    },
    {
        id:"5",
        img:"/card5.png",
        title:"Dates Value Pouch Dates Value",
        dish:"Driedfruit",
        prise:"$78.00",
        prise2:"$56.00",
    },
    {
        id:"6",
        img:"/card6.png",
        title:"Mango - Kesar",
        dish:"Fruits",
        prise:"$65.00",
        prise2:"$62.00",
    },
    {
        id:"7",
        img:"/card7.png",
        title:"Coffee with chocolate cream",
        dish:"Coffee",
        prise:"$65.00",
        prise2:"$62.00",
    },
    {
        id:"8",
        img:"/card8.png",
        title:"Blue berry",
        dish:"Fruits",
        prise:"$30.00",
        prise2:"$25.00",
    },
    {
        id:"9",
        img:"/card9.png",
        title:"Mixed Nuts & Almonds Dry Fruits",
        dish:"Driedfruit",
        prise:"$11.00",
        prise2:"$10.00",
    },
];

export const DataCards =[
    {
        id:"1",
        img:"/data1.png",
        title:"Marketing Guide: 5 Steps to Success to way.",
        dish:"June 30,2022 - Organic",
        button:"Read More",
    },
    {
        id:"2",
        img:"/data2.png",
        title:"Best way to solve business deal issue in market.",
        dish:"April 02,2022 - Fruits",
        button:"Read More",
    },
    {
        id:"3",
        img:"/data3.png",
        title:"31 grocery customer service stats know in 2019.",
        dish:"Mar 09,2022 - Vegetables",
        button:"Read More",
    },
    {
        id:"4",
        img:"/data4.png",
        title:"Business ideas to grow your business traffic.",
        dish:"January 25,2022 - Fastfood",
        button:"Read More",
    },
    {
        id:"5",
        img:"/data5.png",
        title:"Marketing Guide: 5 Steps way to Success.",
        dish:"December 10,2021 - Fruits",
        button:"Read More",
    },
];

export const DataFashion = [
    {
        id:"1",
        img:"/aa1.png",
        title:"Clothes",
        dish:"320 Items",
        sala:"30%",
    },
    {
        id:"2",
        img:"/aa2.png",
        title:"watches",
        dish:"65 Items",
        sala:"",
    },
    {
        id:"3",
        img:"/aa3.png",
        title:"Dresses",
        dish:"548 Items",
        sala:"15%",
    },
    {
        id:"4",
        img:"/aa4.png",
        title:"glasses",
        dish:"48 Items",
        sala:"10%",
    },
    {
        id:"5",
        img:"/aa5.png",
        title:"hat & caps",
        dish:"59 Items",
        sala:"",
    },
    {
        id:"6",
        img:"/aa6.png",
        title:"Shorts",
        dish:"845 Items",
        sala:"",
    },
];

export const DataProductFashion = [
    {
        id:"1",
        img:"/fashion1.png",
        name:"Men's wear printed shirt",
        dish:"Fashion",
        prise:"$56.00",
        prise2:"$45.00",
        sale:"Sale",
    },
    {
        id:"2",
        img:"/fashion2.png",
        name:"Princess Look fashion Dress",
        dish:"women's wear",
        prise:"$30.00",
        prise2:"$25.00",
        sale:"Sale",
    },
    {
        id:"3",
        img:"/fashion3.png",
        name:"Women's sport shoes",
        dish:"Sports",
        prise:"$65.00",
        prise2:"$46.00",
        sale:"",
    },
    {
        id:"4",
        img:"/fashion4.png",
        name:"Body Lotion for Dry Skin",
        dish:"Body Lotion",
        prise:"$85.00",
        prise2:"$78.00",
        sale:"Sale",
    },
    {
        id:"5",
        img:"/fashion5.png",
        name:"Liquid Matte Lipstick",
        dish:"Lipstick",
        prise:"$50.00",
        prise2:"$45.00",
        sale:"NEW",
    },
];

export const DataProductFashions = [
    {
        id:"1",
        img:"/fashion1.png",
        name:"Men's wear printed shirt",
        dish:"Fashion",
        prise:"$56.00",
        prise2:"$45.00",
        sale:"Sale",
    },
    {
        id:"2",
        img:"/fashion2.png",
        name:"Princess Look fashion Dress",
        dish:"women's wear",
        prise:"$30.00",
        prise2:"$25.00",
        sale:"Sale",
    },
    {
        id:"3",
        img:"/fashion3.png",
        name:"Women's sport shoes",
        dish:"Sports",
        prise:"$65.00",
        prise2:"$46.00",
        sale:"",
    },
    {
        id:"4",
        img:"/fashion4.png",
        name:"Body Lotion for Dry Skin",
        dish:"Body Lotion",
        prise:"$85.00",
        prise2:"$78.00",
        sale:"Sale",
    },
    {
        id:"5",
        img:"/fashion5.png",
        name:"Liquid Matte Lipstick",
        dish:"Lipstick",
        prise:"$50.00",
        prise2:"$45.00",
        sale:"NEW",
    },
    {
        id:"6",
        img:"/fashion6.png",
        name:"Men's wear printed shirt",
        dish:"Fashion",
        prise:"$56.00",
        prise2:"$45.00",
        sale:"Sale",
    },
    {
        id:"7",
        img:"/fashion7.png",
        name:"Princess Look fashion Dress",
        dish:"women's wear",
        prise:"$30.00",
        prise2:"$25.00",
        sale:"Sale",
    },
    {
        id:"8",
        img:"/fashion8.png",
        name:"Women's sport shoes",
        dish:"Sports",
        prise:"$65.00",
        prise2:"$46.00",
        sale:"",
    },
    {
        id:"9",
        img:"/fashion9.png",
        name:"Body Lotion for Dry Skin",
        dish:"Body Lotion",
        prise:"$85.00",
        prise2:"$78.00",
        sale:"Sale",
    },
    {
        id:"10",
        img:"/fashion10.png",
        name:"Liquid Matte Lipstick",
        dish:"Lipstick",
        prise:"$50.00",
        prise2:"$45.00",
        sale:"NEW",
    },
];

export const DataItem = [
    {
        id:"1",
        img:"/item1.png",
        title:"Men's stylish printed shirt",
        dish:"Fashion",
        prise:"$45.00",
        prise2:"$42.00",
    },
    {
        id:"2",
        img:"/item2.png",
        title:"Cotton Clothes Sets for Boys",
        dish:"Baby Wear",
        prise:"$30.00",
        prise2:"$25.00",
    },
    {
        id:"3",
        img:"/item3.png",
        title:"Men's Leather Belt",
        dish:"Belt",
        prise:"$65.00",
        prise2:"$62.00",
    },
    {
        id:"4",
        img:"/item4.png",
        title:"Long lasting perfume",
        dish:"perfume",
        prise:"$11.00",
        prise2:"$10.00",
    },
];
export const DataPated = [
    {
        id:"1",
        img:"/rated1.png",
        title:"Rose Gold Earring",
        dish:"jewellery",
        prise:"$65.00",
        prise2:"$62.00",
    },
    {
        id:"2",
        img:"/rated2.png",
        title:"Men's Wear printed shirt",
        dish:"Fashion",
        prise:"$78.00",
        prise2:"$65.00",
    },
    {
        id:"3",
        img:"/rated3.png",
        title:"Women's casual shoes",
        dish:"shoes",
        prise:"$30.00",
        prise2:"$25.00",
    },
    {
        id:"4",
        img:"/rated4.png",
        title:"anti dandruff shampoo",
        dish:"shampoo",
        prise:"$30.00",
        prise2:"$25.00",
    },
];
export const DataSelling = [
    {
        id:"1",
        img:"/selling1.png",
        title:"Liquid Matte Lipstick",
        dish:"Lipstick",
        prise:"$55.00",
        prise2:"$50.00",
    },
    {
        id:"2",
        img:"/selling2.png",
        title:"Women's wallet Hand Purse",
        dish:"wallet",
        prise:"$55.00",
        prise2:"$50.00",
    },
    {
        id:"3",
        img:"/selling3.png",
        title:"Long lasting perfume",
        dish:"perfume",
        prise:"$11.00",
        prise2:"$10.00",
    },
    {
        id:"4",
        img:"/selling4.png",
        title:"Cotton Clothes Sets for Boys",
        dish:"Baby Wear",
        prise:"$35.00",
        prise2:"$25.00",
    },
];
export const DataCard =[
    {
        id:"1",
        img:"/data1.png",
        title:"Marketing Guide: 5 Steps to Success to way.",
        dish:"June 30,2022 - Organic",
        dish2:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        button:"Read More",
    },
    {
        id:"2",
        img:"/data2.png",
        title:"Best way to solve business deal issue in market.",
        dish:"April 02,2022 - Fruits",
        dish2:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        button:"Read More",
    },
    {
        id:"3",
        img:"/data3.png",
        title:"31 grocery customer service stats know in 2019.",
        dish:"Mar 09,2022 - Vegetables",
        dish2:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        button:"Read More",
    },
    {
        id:"4",
        img:"/data4.png",
        title:"Business ideas to grow your business traffic.",
        dish:"January 25,2022 - Fastfood",
        dish2:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        button:"Read More",
    },
    {
        id:"5",
        img:"/data5.png",
        title:"Marketing Guide: 5 Steps way to Success.",
        dish:"December 10,2021 - Fruits",
        dish2:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        button:"Read More",
    },
    {
        id:"6",
        img:"/data6.png",
        title:"15 customer service stats idea know in 2023.",
        dish2:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        dish:"December 10,2021 - Fruits",
        button:"Read More",
    },
];